config/routes.rb
Rails.application.routes.draw do

  devise_for :accounts, controllers: { 
      confirmations: 'accounts/confirmations'
  }  
  
  devise_for :users, controllers: { 
      registrations: 'users/registrations' 
  }  
  
  get 'guest/index'
  
  root 'guest#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/templates/_admin_sign_up.html.erb
<div class="text-center">
    <h2>Create Your Account</h2>
</div>

<div class="row justify-content-center devise-form">
    <%= form_for new_user_registration_path do |f| %>
    <%= devise_error_messages! %>

    <div class="form-group">
        <%= f.label :first_name %><br />
        <%= f.text_field :first_name, class: 'form-control', placeholder: "First name", autofocus: true %>
    </div>

    <div class="form-group">
        <%= f.label :last_name %><br />
        <%= f.text_field :last_name, class: 'form-control', placeholder: "Last name", autofocus: true %>
    </div>
    
    <div class="form-group">
        <%= f.label :role %><br />
        <%= f.text_field :role, class: 'form-control', value: 'admin'  %>
    </div>
    
    <div class="form-group">
        <%= f.label :company_name %><br />
        <%= f.text_field :company_name, value: @account.company_name %>
    </div>
  
    <div class="form-group">
        <%= f.label :company_id %><br />
        <%= f.text_field :company_id, value: @account.id %>
    </div>
  
    <div class="form-group">
        <%= f.label :email %><br />
        <%= f.text_field :email, value: @account.email %>
    </div>
    
    <div class="text-center">
        <div class="actions">
            <%= f.submit "Create Account", class: 'btn btn-primary' %>
        </div>
    </div>
    
    <% end %>
</div>

app/views/templates/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark sticky-top">
    
    <%= link_to image_tag("Barweiser_Full_Wht.png"), root_path, class: 'navbar-brand' %>
  
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="main-nav">
        
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <%= link_to "SIGN UP", new_account_registration_path, class: 'nav-link' %>
            </li>
            
            <li class="nav-item">
                <%= link_to "SIGN IN", root_path, class: 'nav-link' %>
            </li>
            
            <li class="nav-item menu-footer d-md-none">
                <%= link_to image_tag("BarweiserSM_Blk.png"), root_path, class: 'nav-link' %>
            </li>      
        </ul>
        
    </div>
    
</nav>